### ISSUE TITLE
DOC: pybricks.com: MicroPython over WebBlueTooth

### ISSUE THREAD

**Issue by westurner** [louisfoster/awesome-web-serial#3]
- https://github.com/quobit/awesome-python-in-education/issues/50

**Comment by louisfoster** [comment]
Without any information on how this relates to the Web Serial API, I will close this issue.

**Comment by westurner** [comment]
NAICT, in putting together links for
https://news.ycombinator.com/item?id=38005027 [1] I confused WebSerial, Web
Bluetooth, and WebUSB.

Pybricks flashes micropython to LEGO hubs over WebBluetooth

[1] links to a USB to 2x20 pin interface from which a serial adapter could
probably be made in lieu of a RP2040 or a USB-to-RS-232 serial cable; and
then WebSerial over those. I think, idk
